spring:
  datasource:
    url: jdbc:mariadb://pitter.c7pcpzhgejgg.ap-northeast-2.rds.amazonaws.com:3306/pitter
    username: pitter
    password: pitteradmin1!
    driverClassName: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        check_nullability: true
        show_sql: true
        format_sql: true
      logging.level:
        org.hibernate.SQL: debug
        org.hibernate.type: trace
    database-platform: org.hibernate.dialect.MySQL8Dialect